### ISSUE TITLE
Remove SQLite support 

### ISSUE THREAD

**Issue by hatched** [hatched/ghost-charm#24]
Once a single machine Ghost & MySQL bundle is created there is really no use for the SQLite support any longer. It adds complexity in the charm and creates many problems for horizontal scalability.

**Comment by mbruzek** [comment]
I use this charm on a small droplet on Digital Ocean which only has 512MB of RAM. I use SQLite to avoid the memory consumption of MySQL.  I would encourage you to keep the SQLite support.

**Comment by hatched** [comment]
I haven't ran into any issues updating the feature set while maintaining this support. I'll keep it in.
